// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "tebpardaz/server/views/layouts"

// AdminLoginView مدل صفحه ورود ادمین است.
type AdminLoginView struct {
	ErrorMessage string
	OTPRequired  bool
	Username     string
}

// AdminLogin صفحه ورود پنل ادمین را با طراحی Glassmorphism رندر می‌کند.
// ورودی: view شامل پیام خطای اختیاری. خروجی: کامپوننت templ.
func AdminLogin(view AdminLoginView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"admin-shell admin-login-shell\"><div class=\"glass-orbs-container\" aria-hidden=\"true\"><div class=\"glass-orb glass-orb-1\"></div><div class=\"glass-orb glass-orb-2\"></div><div class=\"glass-orb glass-orb-3\"></div></div><main class=\"admin-login-main\"><div class=\"admin-login-card\"><div class=\"admin-login-brand\"><div class=\"admin-login-brand-icon\"><i class=\"fa-solid fa-shield-halved\"></i></div><div><h1 class=\"admin-login-title\">ورود به پنل مدیریت</h1><p class=\"admin-login-subtitle\">سامانه یکپارچه نوبت\u200cدهی طب\u200cپرداز</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if view.ErrorMessage != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"admin-login-error\" role=\"alert\"><i class=\"fa-solid fa-circle-exclamation\"></i> <span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(view.ErrorMessage)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/login.templ`, Line: 41, Col: 32}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form method=\"post\" action=\"/admin/login\" class=\"admin-login-form\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if view.OTPRequired {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<input type=\"hidden\" name=\"username\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(view.Username)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/login.templ`, Line: 47, Col: 65}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"><p class=\"admin-login-subtitle mb-3\">کد تایید به شماره\u200cهای مجاز ارسال شد.</p><label class=\"admin-login-label\" for=\"admin-otp\">کد تایید</label> <input id=\"admin-otp\" class=\"ui-field w-full\" type=\"text\" name=\"otp_code\" required inputmode=\"numeric\" autocomplete=\"one-time-code\" maxlength=\"8\" placeholder=\"کد ۵ رقمی را وارد کنید\"> <button class=\"ui-btn ui-btn-primary ui-btn-block mt-2\" type=\"submit\"><i class=\"fa-solid fa-shield-halved ml-1.5\"></i> <span>تایید و ورود</span></button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<label class=\"admin-login-label\" for=\"admin-username\">نام کاربری</label> <input id=\"admin-username\" class=\"ui-field w-full\" type=\"text\" name=\"username\" required autocomplete=\"username\" placeholder=\"نام کاربری خود را وارد کنید\"> <label class=\"admin-login-label\" for=\"admin-password\">رمز عبور</label> <input id=\"admin-password\" class=\"ui-field w-full\" type=\"password\" name=\"password\" required autocomplete=\"current-password\" placeholder=\"رمز عبور خود را وارد کنید\"> <button class=\"ui-btn ui-btn-primary ui-btn-block mt-2\" type=\"submit\"><i class=\"fa-solid fa-right-to-bracket ml-1.5\"></i> <span>دریافت کد ورود</span></button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</form></div></main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Document(layouts.PageHead{
			Title:  "ورود ادمین | طب‌پرداز",
			Robots: "noindex, nofollow",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
